/// 背景颜色
const THEME_BACKGROUND_COLOR = 0xFF3B3E48;

/// 文字颜色1
const THEME_TEXT_1_COLOR = 0xFFFFFFFF;

/// 文字颜色2
const THEME_TEXT_2_COLOR = 0xFFACAFB1;

/// 文字颜色 提示
const THEME_TEXT_HINT_COLOR = 0xFF585E6D;
